logging:
  file:
    name: logs/application.log
spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
     username: root
     password: root
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
       ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 8085
  session-timeout: 30
